
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - media_data:/app/media
    environment:
      - DEBUG=True

volumes:
  sqlite_data:
  media_data:
